apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fran123
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com//.git
    targetRevision: HEAD
    path: charts/static-web
    helm:
      valueFiles:
        - ../../app-values/fran123/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
